### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by amyspark**
I noticed that this package had an outdated version of `postcss`.
I've updated the dependencies' versions, and run the tests. Everything should be OK.

### CODE REVIEW

**Comment by amyspark** [comment]
The failing test (Node.js 0.12) needs the `--harmony` flag.

**Comment by sdempsey** [comment]
+1  Please merge.

This error this morning while trying to setup autoprefixer:

`Your current PostCSS version is 4.1.16, but autoprefixer uses 6.0.7. Perhaps this is the source of the error below.`
`Fatal error: css.walkAtRules is not a function`

**Comment by donlion** [comment]
+1

**Comment by donlion** [comment]
@nDmitry Could you merge this one?

**Comment by C-Lodder** [comment]
@donlion @amyspark @sdempsey I've forked the project and updated all dependencies: https://github.com/C-Lodder/grunt-postcss-x

Also released on NPM

**Comment by nDmitry** [comment]
updated

**Pull request closed without merging**
