### PR TITLE
Add an ability to use options.processor as a function

### PR DESCRIPTION
**Pull request by soul-wish**
Hi Dmitry. What do you think about ability to use a function in `options.processor`? In this case it will be possible to configure a list of PostCSS post-processors dynamically (depending on Grunt environment etc.). Thanks for such a great plugin, anyway!

### CODE REVIEW

**Comment by nDmitry** [comment]
I think that's useful, thanks!

**Comment by soul-wish** [comment]
Awesome! Thanks, Dmitry 👍

**Comment by soul-wish** [comment]
Just curious. Are you planning to publish a new release on npm in the nearest future?

**Comment by nDmitry** [comment]
I'm going to publish today.

**Comment by soul-wish** [comment]
That's cool, thanks!

**Pull request merged**
