### PR TITLE
0.7.0

### PR DESCRIPTION
**Pull request by jonathantneal**
Update dependencies:
- Chalk 1.1.1 (minor)
- Diff 2.1.2 (major)
- PostCSS 5.0.8 (minor)

Update development dependencies:
- Grunt JSHint 0.11.3 (minor)
- Grunt Nodeunit 0.4.5 (minor)
- Load grunt tasks 0.3.0 (major)
- PostCSS SCSS 0.1.2 (minor)
- Time Grunt 1.2.1 (major)

Update package.json
- PostCSS 5+ requires Node .12+
- Node .12+ supports Promises natively

See:
https://twitter.com/PostCSS/status/647361395156193281
https://github.com/postcss/postcss/blob/master/package.json#L6

### CODE REVIEW

**Comment by ben-eb** [comment]
:+1:

**Comment by nDmitry** [comment]
Thanks, I will use some of that when it's time to release a new version, FYI we don't have to update minor and patch version numbers if it's a caret (^) version.

**Comment by jonathantneal** [comment]
When is it time? Is there a release schedule?

**Comment by nDmitry** [comment]
There isn't, just want merge a PR first. Besides I'm not gonna bump engine version, PostCSS still works with 0.10 with Promise polyfill, so this one won't be merged, sorry.

**Pull request closed without merging**
