### PR TITLE
Update to grunt v1.0.0

### PR DESCRIPTION
**Pull request by alorek**

### CODE REVIEW

**Comment by ChristianSchramm** [comment]
Hey Dimitry,

is it possible to merge the pullrequest and release a new npm build? That would be great.

Thanks a lot

**Comment by nDmitry** [comment]
https://github.com/nDmitry/grunt-postcss/blob/master/package.json#L35

**Comment by ChristianSchramm** [comment]
Thank you very much, that was really fast, really cool. But please release a new npm package, so we will get the new version when using npm install.

**Comment by nDmitry** [comment]
I have updated grunt version and released a new version back in February. You should install the latest version (0.8.0). If you use ~ or ^ notation, npm update won't do it automatically. https://docs.npmjs.com/misc/semver

**Pull request closed without merging**
